### ISSUE TITLE
Cannot create .makerbot files from MakerBot Print v4

### ISSUE THREAD

**Issue by peter-russell** [tjhorner/MakerbotWebUI#8]
MakerBot Print v4 no longer has the ability to export to `.makerbot` files.

Can `.print` files be used?

**Comment by tjhorner** [comment]
`.print` files contain the raw 3D objects and other metadata, while `.makerbot` files contain the final sliced model. So no, `.print` files cannot be used.

Is there really no way to create `.makerbot` files from MakerBot Print anymore?

**Comment by tjhorner** [comment]
I just updated to the latest version of MakerBot Print, and I am still able to export to `.makerbot` files.

Here's how:

- Select "Add a Printer" from the printer selector
<img width="150" alt="image" src="https://user-images.githubusercontent.com/2646487/56519547-2d3a3580-64f7-11e9-863a-8e9b982a0338.png">

- "Add an unconnected printer"
- Select your printer type
- Once added, select your new "Export Only" printer type and you will be able to export files to `.makerbot`

**Comment by tjhorner** [comment]
Closing this since it seems to be solved
